# constants.py
import pygame

# Window Dimensions
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

# Milestone 25: Infinite Canvas World Dimensions
WORLD_WIDTH = 5000
WORLD_HEIGHT = 5000

# Milestone 25: Grid Snapping Configuration
GRID_SIZE = 40
GRID_COLOR = (100, 100, 100)
GRID_ALPHA = 50

# Milestone 25: Camera Panning Speed
CAMERA_PAN_SPEED = 300.0  # pixels per second

# Physics Configuration
PHYSICS_STEP = 1 / 60.0
GRAVITY = (0, 900)  # Pygame Y goes down, so positive Y is "down" in Pymunk too

# Collision Types
COLLISION_TYPE_BASKET = 2
COLLISION_TYPE_CANNON = 3
COLLISION_TYPE_FACTORY_TOP = 5
COLLISION_TYPE_SINK_TOP = 6

# Milestone 22 Payload Controls
DEFAULT_PAYLOAD_TTL = 50
DEFAULT_PAYLOAD_COST = 100.0
DEFAULT_PAYLOAD_DROP_DEAD_AGE = 5.0
MAX_ROUTING_DEPTH = 1000

# Milestone 23 Data Source Controls
DEFAULT_PAYLOAD_SCORE = 100
MAX_BATCH_QUEUE_POLLS = 10

# Milestone 24 Data Sink Controls
SINK_ROTATION_MAX_OBJECTS = 10
SINK_ROTATION_SECONDS = 180
SINK_EXPORT_DIR = "exports"
SINK_MCP_TIMEOUT_SECONDS = 5.0
SINK_WORKER_JOIN_TIMEOUT_SECONDS = 8.0
SINK_INGEST_STATE_COOLDOWN = 0.08

# Factory Runtime Tuning
FACTORY_COOLDOWN_SECONDS = 0.5
FLOATING_UPWARD_ACCELERATION = 500.0
FLOATING_TIMEOUT_SECONDS = 2.0
FLOATING_LABEL_RISE_SPEED = 22.0

# Colors (RGB)
COLOR_BACKGROUND = (30, 30, 30)
COLOR_TEXT = (200, 200, 200)
COLOR_RAMP = (150, 150, 150)
COLOR_BALL = (255, 100, 100)
COLOR_BOUNDARY = (100, 100, 100)
