import time
from typing import Any, Dict, List, Optional
import pygame
import pymunk
import random

try:
    from faker import Faker
except ImportError:
    Faker = None

import constants
from entities.base import FlowEntity

class FakerSource(FlowEntity):
    """
    Milestone 40: Synthetic Data Generator.
    Emits payload balls containing data generated by the Faker library.
    """
    can_accept_input = False
    can_provide_output = True

    def __init__(self, space: pymunk.Space, x: float, y: float, variant_name: str = "faker_source"):
        super().__init__(space, x, y, variant_name)
        
        # Default Properties
        self.properties.setdefault("faker_schema", {"name": "name", "email": "email", "job": "job"})
        self.properties.setdefault("emit_interval", 2.0)
        self.properties.setdefault("random_seed", None)
        self.properties.setdefault("output_variant", "payload_ball")
        self.properties.setdefault("exit_velocity", 150.0)
        self.properties.setdefault("exit_angle", 0.0)
        self.properties.setdefault("active_side", "bottom")
        self.properties.setdefault("width", 96.0)
        self.properties.setdefault("height", 96.0)
        
        self.emit_timer = 0.0
        self.fake = None
        
        # Init Faker
        if Faker:
            seed = self.get_property("random_seed")
            self.fake = Faker()
            if seed is not None:
                self.fake.seed_instance(int(seed))
        
        self.visual_state = "IDLE"

    def update_logic(self, dt: float, game_state: Dict[str, Any], entities: List[Any], active_instances: Optional[Dict[str, Any]] = None):
        if game_state.get("mode") != "PLAY":
            return

        interval = float(self.get_property("emit_interval", 2.0))
        self.emit_timer += dt
        
        if self.emit_timer >= interval:
            self.emit_timer = 0.0
            self._emit_ball(entities, active_instances)

    def _emit_ball(self, entities, active_instances):
        # Local import to avoid circular dependency
        from main import create_part
        
        variant = str(self.get_property("output_variant", "payload_ball"))
        ball = create_part(self.space, self.body.position.x, self.body.position.y, variant)
        
        if ball:
            schema = self.get_property("faker_schema", {})
            data = {}
            
            if self.fake:
                for key, provider in schema.items():
                    try:
                        method = getattr(self.fake, str(provider))
                        data[key] = method()
                    except Exception as e:
                        data[key] = f"error: {e}"
            else:
                data = {"error": "faker library not installed"}

            if hasattr(ball, "payload"):
                if "data" not in ball.payload:
                    ball.payload["data"] = {}
                ball.payload["data"].update(data)
                ball.payload["origin_uuid"] = self.uuid

            entities.append(ball)
            if active_instances is not None:
                active_instances[ball.uuid] = ball
            
            # Eject with state 10 (Standard for Source)
            res = self.resolve_exit_path(ball, 10, entities, active_instances)
            self.visual_state = "IDLE"

    def draw(self, surface, camera=None, **kwargs):
        super().draw(surface, camera, **kwargs)
        # Optional: Add small indicator for Faker active
        pass
